{{- if .Values.btcpayserver.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "btcpayserver.fullname" . }}
  labels:
    {{- include "btcpayserver.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "btcpayserver.fullname" . }}
  minReplicas: {{ .Values.btcpayserver.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.btcpayserver.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.btcpayserver.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.btcpayserver.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.btcpayserver.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.btcpayserver.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
