apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbxplorer-datadir
spec:
  storageClassName: {{ .Values.nbxplorer.PersistentVolumeClaim.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-datadir
spec:
  storageClassName: {{ .Values.bitcoind.PersistentVolumeClaim.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-wallet-datadir
spec:
  storageClassName: {{ .Values.bitcoind.PersistentVolumeClaim.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor-datadir
spec:
  storageClassName: {{ .Values.bitcoind.PersistentVolumeClaim.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btcpay-datadir
spec:
  storageClassName: {{ .Values.btcpayserver.PersistentVolumeClaim.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi