{{- if .Values.btcpayserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "btcpayserver.serviceAccountName" . }}
  labels:
    {{- include "btcpayserver.labels" . | nindent 4 }}
  {{- with .Values.btcpayserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
