apiVersion: v1
kind: Service
metadata:
  name: btcpayserver
  labels:
    {{- include "btcpayserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.btcpayserver.service.type }}
  ports:
    - port: {{ .Values.btcpayserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "btcpayserver.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: nbxplorer
  labels:
    {{- include "nbxplorer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nbxplorer.service.type }}
  ports:
    - port: {{ .Values.nbxplorer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nbxplorer.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: bitcoind-rpc
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bitcoind.service.type }}
  ports:
    - port: {{ .Values.bitcoind.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "bitcoind.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bitcoind.service.type }}
  ports:
    - port: {{ .Values.bitcoind.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bitcoind.selectorLabels" . | nindent 4 }}